name: Publish Python 🐍 distributions 📦 to PyPI

on:
  create:
    tags:

jobs:
  run-lint-workflow:
    uses: ./.github/workflows/lint.yml

  build:
    name: Build code
    runs-on: ubuntu-latest
    needs: run-lint-workflow
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Install dependencies
        run: python -m pip install -e ".[build]"
      - name: Build
        run: pipx run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/

  publish-to-test-pypi:
    name: Release on TestPyPi
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    environment: TestPyPi
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/
      - name: Publish 📦 to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish-to-pypi:
    name: Release on PyPi
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    environment: PyPi
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/
      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
